### ISSUE TITLE
Guys if you have any comments, please leave them here

### ISSUE THREAD

**Issue by SarvarKh** [wandji20/Capstone-Online-Shop#2]
Guys if you have any comments, please leave them here

**Comment by Byabasaija** [comment]
the project looks good. just a tip, modify your home page title in the title tags, same applies to the items page.
Otherwise good work and great use of bootstrap

**Comment by SarvarKh** [comment]
The project looks nice and clean. The only thing, as was mentioned, is the grid-gap) You may try to apply the following: col-md-offset-2

**Comment by Andrik27001** [comment]
Everything looks great, there are just some improvements you can do! 
- The inputs of the left bar should be a checkbox input and not radio input, and they should be displayed one over the other
- You can make the images a link as well
- You can add some margins or padding between the images.

**Comment by apricot12** [comment]
**It looks great at a glance but if you could, try to fix the following :**

- The buttons, try to use a tags and style with css, it'd look flatter.

- The input fields should have no styling, including borders and be have 90 degree angles.
